### ISSUE TITLE
Buy and integrate higher quality temp sensors

### ISSUE THREAD

**Issue by neogeek83** [neogeek83/arduino-temp-control#4]
The current sensor isn't very accurate. Research has shown we'd be better served with DHT44 to replace the DHT11 we're using now.

**Comment by thefirstnutzo** [comment]
https://www.amazon.com/AM2302-Digital-Temperature-Humidity-Dehumidifier/dp/B00RX1F4PU/ref=sr_1_11?ie=UTF8&qid=1498521541&sr=8-11&keywords=dht22

**Comment by neogeek83** [comment]
k, i bought 4 of those, eta July 18, 2017 - Aug. 8, 2017

**Comment by neogeek83** [comment]
Finished and included in TempReadout4
